spring.application.name=Local

server.port=8080
server.servlet.context-path=/local

logging.level.root=trace

spell.checker.ownerName=Tech Pioneers Hub
spell.checker.version=V1.2


# DB Configs
db.username=admin
db.password=123
db.database=db
db.url=jdbc:mysql://localhost:3306/db
db.connection-pool-properties.max-idle-connections=100
db.connection-pool-properties.max-open-connections=50
db.connection-pool-properties.timeout=800