spring.application.name=PRD

server.port=8082
server.servlet.context-path=/prd

logging.level.root=info

spell.checker.ownerName=Tech Pioneers Hub
spell.checker.version=V1.0

# DB Config
db.username=tphprod
db.password=TPH#$@!u31DdF
db.database=prod
db.url=jdbc:mysql://192.168.0.203:3306/prod
db.connection-pool-properties.max-open-connections=200
db.connection-pool-properties.max-idle-connections=80
db.connection-pool-properties.timeout=90
